### PR TITLE
Add GamepadControl plugin.

### PR DESCRIPTION
**Pull request by SamuelTS**
Hello @pissang ☺️

I propose you this gamepad control plugin.
It works fine with Xbox One Controller. 👍
I think it works also with X360 & PS4 pads.

About integration, I'm not sure about this:

```
import FreeControl$84 from './plugin/FreeControl';
import GamepadControl$117 from './plugin/GamepadControl';
import GestureMgr$85 from './plugin/GestureMgr';
...
GamepadControl: GamepadControl$117,
```

Should `Class$number` restarting from 85?

### CODE REVIEW

**Comment by pissang** [comment]
Wow!! It's a big feature!! Can it be integrated into FreeControl and OrbitControl so we can also use gamepad to orbit the camera.

The `src/claygl.js` can be generated automatically by running `npm run gen:entry`.

**Comment by SamuelTS** [comment]
>Can it be integrated into FreeControl and OrbitControl so we can also use gamepad to orbit the camera.

You can use simultaneously OrbitControl and GamepadControl. FreeControl: untested but should coworks.

**Comment by pissang** [comment]
> You can use simultaneously OrbitControl and GamepadControl. FreeControl: untested but should coworks.

Not sure if I understand you correctly, what I mean is more like the `FreeControl` supports both keyboard and gamepad. So does the `OrbitControl`, which now supports both keyboard/mouse and mobile touch. If so, we can use gamepad for more kinds of controls.

**Comment by SamuelTS** [comment]
This is how I tested both controls in my application:

```
		this._orbitControl = new clay.plugin.OrbitControl({
			target: this._camera,
			domElement: app.container
		});

		this._gamepadControl = new clay.plugin.GamepadControl({
			target: this._camera,
			onStandardGamepadReady: PBR.Viewport.onStandardGamepadReady,
			onGamepadDisconnected: PBR.Viewport.onGamepadDisconnected
		});

		this._orbitControl.update(app.frameTime);
		this._gamepadControl.update(app.frameTime);
```
I don't know if it's best way but it works very well :=)

**Comment by pissang** [comment]
> Not sure to understand I too. ^^ Do you want to merge FreeControl with GamepadControl?

Yes, and I will update the OrbitControl to support using gamepad then ( Will allow using gamepad stick to rotate the camera.

**Comment by SamuelTS** [comment]
> Yes, and I will update the OrbitControl to support using gamepad then ( Will allow using gamepad stick to rotate the camera.

Feel free to adapt my code.

**Pull request merged**
